travis:
  secure:
    BINSTAR_TOKEN: lxnn7dD5aPofTPiO4lGoBR+bADCW8sJ9yYs/VvSDNZ1U/k15awEWsfVFv2r1kg7mAigNuwjEh0ndDBqtPhyAH+BmEP9PD4ny8Ndxa5ThhDprT33ERUQb7t8MeHq8U3ojSGFt7UPqicC3DJ8UKDwfDaBlLK8gsajvLN/uS3GwrU5oV8MmiZShuG8hj3lCaQEvBbw/CC5oka9ELKw6IGvMHCvtaqVJzbysxhFZiq1bKpDL9tm+rp7fsDLviQ7z/Ri2c7ekxEj4blUC0vDGvVNguJ4+FOPEj8/3mGo4jnh+TTbHFb3lYR6ellunQJplqSPpiMfi4xCKcyyHYACWFD5PyqQCPGbNtJrELoDwY/WmOqSfxt2XNT1+O/zFPGVeTmq3Ry5uyzd2OqDwmpuhpA3PYXei3yjQxCH0E/mUJaHe3/b8YxQ9auFxDzyb8aMdsgdONvBrkx4CD2PX2nFxzwShFieptZq/NEDmjH4e4EWm0+f8Wn52LelGNCNNYwcFYVK2NpovBdvvxEzTvZDYnRgN2kNUaA3xFsgaO681V5Zd/09MEtBtc5n/on7/BzZkHg27S+U6dn6YPZbk3+uh5PCFXjD6Wn9AjmWlWUIBtGOBY2kHazEH1KMKpE/W58XYrPSR0q9W8nRg0gzZGtNwzxghOIJrix5/2p9afP7pMa1cohA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
